enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  OnboardingScreen = "OnboardingScreen",
  ChooseRoleScreen = "ChooseRoleScreen",
  LocationAllow="LocationAllow",
  CreatePin ="CreatePin",
  ReadyScreen = "ReadyScreen",
  LoginScreen = "LoginScreen",
  SignUpScreen = "SignUpScreen",
  OtpScreen = "OtpScreen",
  FAQScreen="FAQScreen",
  BuyScreen="BuyScreen",
  SellScreen = "SellScreen",
  BuyDetail = "BuyDetail",
  SellDetail = "SellDetail",
  ConfirmSwapScreen="ConfirmSwapScreen",
  DonationTrackingDetail = "DonationTrackingDetail",
  DonationDetail  = "DonationDetail",
  BottomTabs="BottomTabs",
  CreatePassword = "CreatePassword",
  PasswordReset = "PasswordReset",
  EarnDetail ="EarnDetail",
  PaymentDetails="PaymentDetails",
  DashBoardScreen = "DashBoardScreen",
  ProductDetailScreen = "ProductDetailScreen",
 colorList = "colorList",
 Notification ="Notification",
 DocumentScreen = "DocumentScreen",
 SubmittingScreen ="SubmittingScreen",
 DonationScreen = "DonationScreen",
Address = "Address",
NotificationsSetting ="NotificationsSetting",
OrederList = "OrderList",
OrderDetail = "OrderDetail",
NewAddress="NewAddress",
paymentMethod="PaymentMethod",
creditLimit="CreditLimit",
LimitDetail="LimitDetail",
AboutLimit = "AboutLimit",
InvoiceDetail ="InvoiceDetail",
ChatDetail = "ChatDetail",
LoanForm = "LoanForm",
  setting = "Setting",
  language = "Language",
  personalInfo = "PersonalInfo",
  changePassword = "ChangePassword",
  card = "card",
  condition = "Conditions",
  socity = "Socity",
  AddContractWithType = "AddContractWithType",
  About="About",
  Policy ="Policy",

  }

export default ScreenNameEnum;
